name: main

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - uses: pnpm/action-setup@v5
      - run: pnpm install --frozen-lockfile
      - run: pnpm run ci
      - uses: codecov/codecov-action@v3
